# Generated by Django 5.0.1 on 2025-10-21 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_borrow_amount', models.DecimalField(decimal_places=2, default=20, max_digits=10)),
                ('available_borrow', models.DecimalField(decimal_places=2, default=20, max_digits=10)),
                ('is_locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_limit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Borrow Limit',
                'verbose_name_plural': 'Borrow Limits',
                'db_table': 'borrow_limit',
            },
        ),
        migrations.CreateModel(
            name='BorrowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_before', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_requested', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrow_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_debit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('repaid', 'Repaid')], default='pending', max_length=20)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('repaid_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Borrow Transaction',
                'verbose_name_plural': 'Borrow Transactions',
                'db_table': 'borrow_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BorrowRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('repaid_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='borrowing.borrowtransaction')),
            ],
            options={
                'verbose_name': 'Borrow Repayment',
                'verbose_name_plural': 'Borrow Repayments',
                'db_table': 'borrow_repayment',
            },
        ),
    ]
