# Generated by Django 5.0.1 on 2025-10-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='aid_recipient',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='kyc_level',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Level 1'), (2, 'Level 2')], default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='phone number'),
        ),
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
