# Generated by Django 4.2.11 on 2025-10-11 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('folders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to=documents.models.user_directory_path)),
                ('file_type', models.CharField(choices=[('txt', 'Text'), ('md', 'Markdown'), ('pdf', 'PDF'), ('doc', 'Word Document'), ('docx', 'Word Document (DOCX)')], max_length=10)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='folders.folder')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['owner', 'folder'], name='documents_d_owner_i_9f7a17_idx'), models.Index(fields=['file_type'], name='documents_d_file_ty_1bb410_idx')],
            },
        ),
    ]
