"""
Django settings for document_manager project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z&x&9er45hkfe3nb4tgf#_iga0(z1xm0_-met5&+19q)+mtz-b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Local apps
    'accounts',
    'dashboard',
    # New lending platform apps
    'whatsapp_auth',
    'kyc',
    'scoring',
    'borrowing',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'document_manager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'document_manager.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# Authentication settings
LOGIN_URL = 'whatsapp_auth:request_otp'
LOGIN_REDIRECT_URL = 'dashboard:index'
LOGOUT_REDIRECT_URL = 'whatsapp_auth:request_otp'

# Email settings (console backend for development)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'noreply@documentmanager.com'

# File upload settings
MAX_UPLOAD_SIZE = 10 * 1024 * 1024  # 10MB
ALLOWED_FILE_TYPES = ['.txt', '.md', '.pdf', '.doc', '.docx']

# Storage settings
DEFAULT_STORAGE_QUOTA = 1024 * 1024 * 1024  # 1GB

# Security settings
SESSION_COOKIE_AGE = 1209600  # 2 weeks
PASSWORD_RESET_TIMEOUT = 3600  # 1 hour

# ==================== WHATSAPP & LENDING PLATFORM SETTINGS ====================

# WhatsApp/Twilio Configuration
TWILIO_ACCOUNT_SID = config('TWILIO_ACCOUNT_SID', default='')
TWILIO_AUTH_TOKEN = config('TWILIO_AUTH_TOKEN', default='')
TWILIO_WHATSAPP_FROM_NUMBER = config('TWILIO_WHATSAPP_FROM_NUMBER', default='whatsapp:+13604747952')
TWILIO_WHATSAPP_RECEIVER_INVITATION_TEMPLATE_SID = config('TWILIO_WHATSAPP_RECEIVER_INVITATION_TEMPLATE_SID', default='')
TWILIO_WHATSAPP_RECEIVER_OTP_TEMPLATE_SID = config('TWILIO_WHATSAPP_RECEIVER_OTP_TEMPLATE_SID', default='')

# OTP Settings
OTP_VALID_DURATION = 300  # 5 minutes in seconds
OTP_MAX_ATTEMPTS = 3

# KYC Settings
KYC_QUESTIONS = [
    "Say your full name as on your ID. (You can also type.)",
    "Date of birth. Use keypad: DDMMYYYY.",
    "City or village where you live. (You can say nearest market or landmark.)",
    "Mobile money number. Use keypad.",
    "ID type. Say: national ID, voter card, passport, or other.",
    "ID number. Use keypad.",
    "You have a business ? Press 1 Yes, 2 No.",
    "Are you the only owner? Press 1 Yes, 2 No.",
    "What do you do or sell? One sentence.",
    "Loan purpose in one sentence.",
]

KYC_LEVEL_1_THRESHOLD = 10  # All 10 questions completed
KYC_LEVEL_2_REQUIRES = ['business_registration', 'electricity_bill']

# Scoring Settings
BASE_REFERRAL_POINTS = 50
PHONE_BILL_UPLOAD_POINTS = 25

# Borrowing Settings
MAX_INITIAL_BORROW = 20
BORROW_FEE_PERCENT = 5  # 5% fee on borrowed amount
