# Generated by Django 5.0.1 on 2025-10-21 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=100, unique=True)),
                ('rule_type', models.CharField(choices=[('referral', 'Referral'), ('phone_bill', 'Phone Bill'), ('kyc_level_1', 'KYC Level 1'), ('kyc_level_2', 'KYC Level 2'), ('other', 'Other')], max_length=50)),
                ('points_value', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Score Rule',
                'verbose_name_plural': 'Score Rules',
                'db_table': 'score_rule',
            },
        ),
        migrations.CreateModel(
            name='PhoneBillUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_bill_file', models.FileField(upload_to='score/phone_bills/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('score_awarded', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_bill_uploads', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_phone_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phone Bill Upload',
                'verbose_name_plural': 'Phone Bill Uploads',
                'db_table': 'phone_bill_upload',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=50, unique=True)),
                ('referred_phone', models.CharField(max_length=20)),
                ('score_awarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to=settings.AUTH_USER_MODEL)),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral',
                'verbose_name_plural': 'Referrals',
                'db_table': 'referral',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('referral', 'User Referral'), ('phone_bill', 'Phone Bill Upload'), ('admin_adjustment', 'Admin Adjustment'), ('other', 'Other')], max_length=50)),
                ('points_added', models.IntegerField()),
                ('previous_score', models.IntegerField()),
                ('new_score', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Score Log',
                'verbose_name_plural': 'Score Logs',
                'db_table': 'score_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
