# Generated by Django 5.0.1 on 2025-10-21 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('mobile_money_number', models.CharField(blank=True, max_length=50)),
                ('id_type', models.CharField(blank=True, max_length=50)),
                ('id_number', models.CharField(blank=True, max_length=100)),
                ('has_business', models.BooleanField(null=True)),
                ('is_only_owner', models.BooleanField(null=True)),
                ('business_description', models.TextField(blank=True)),
                ('loan_purpose', models.TextField(blank=True)),
                ('all_questions_answered', models.BooleanField(default=False)),
                ('level_1_completed_at', models.DateTimeField(blank=True, null=True)),
                ('business_registration_doc', models.FileField(blank=True, null=True, upload_to='kyc/documents/')),
                ('electricity_bill_doc', models.FileField(blank=True, null=True, upload_to='kyc/documents/')),
                ('level_2_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC Profile',
                'verbose_name_plural': 'KYC Profiles',
                'db_table': 'kyc_profile',
            },
        ),
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('business_registration', 'Business Registration'), ('electricity_bill', 'Electricity Bill'), ('national_id', 'National ID'), ('other', 'Other')], max_length=50)),
                ('document_file', models.FileField(upload_to='kyc/documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_kyc_documents', to=settings.AUTH_USER_MODEL)),
                ('kyc_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='kyc.kycprofile')),
            ],
            options={
                'verbose_name': 'KYC Document',
                'verbose_name_plural': 'KYC Documents',
                'db_table': 'kyc_document',
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_index', models.IntegerField()),
                ('question_text', models.TextField()),
                ('answer', models.TextField()),
                ('answered_at', models.DateTimeField(auto_now=True)),
                ('kyc_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='kyc.kycprofile')),
            ],
            options={
                'verbose_name': 'Questionnaire Response',
                'verbose_name_plural': 'Questionnaire Responses',
                'db_table': 'questionnaire_response',
                'unique_together': {('kyc_profile', 'question_index')},
            },
        ),
    ]
